### PR TITLE
Ported Javascript functionality to PHP

### PR DESCRIPTION
**Pull request by markhazlewood**
I wanted to create a service to expose bullshit via JSON (specifically for a Hipchat integration). I honestly wasn't sure how to do this via Javascript, but I knew I could do it easily in PHP. So I basically did a very simple direct port of the JS source to PHP.

This is my first project contribution and PR, so by all means let me know if I'm not doing it right.  =)

### CODE REVIEW

**Comment by sebpearce** [comment]
Nice work! Have you got it running on a server somewhere? I know a few people that would be happy to have a JSON api for this.

**Comment by markhazlewood** [comment]
Yeah I've actually got it running on my personal site:

http://mhazlewood.org/api/nabs/

**Comment by sebpearce** [comment]
Very cool. If you make another route for it which generates a whole paragraph with a consistent topic, I think it'd be pretty popular as a lorem ipsum generator.

**Comment by markhazlewood** [comment]
Done and done.  =)  

http://www.mhazlewood.org/api/nabs/full
http://www.mhazlewood.org/api/nabs/short

So far this is just deployed to my own site, but I'll work on rolling it into this codebase in some form when I can. Needs some additional documentation and references, plus need some tweaking of the htaccess redirect.

Feel free to suggest a way to promote this for the community.  =D

**Pull request merged**
